name: Haskell with cabal no v2-

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: '8.2.2'
            cabal-install: '2.0'
          #  hvr binary '2.0.0.1'
          - ghc: '8.0.2'
            cabal-install: '1.24'
          #  hvr binary '1.24.0.2'
          - ghc: '7.10.3'
            cabal-install: '1.22'
          #  hvr binary '1.22.9.0'

    steps:
    - uses: actions/checkout@v2
    - uses: khibino/haskell-actions/setup@v1-g7
    # - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal-install }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Clear cabal configuration
      run: |
        rm ~/.cabal/config
        # remove cabal configuration in cache
    - name: Install dependencies
      run: |
        set -ex
        cabal update
        cabal install --jobs=2 --only-dependencies
    - name: Build
      run: |
        set -ex
        cabal configure --enable-tests
        cabal build --jobs=2
    - name: Run tests
      run: |
        set -ex
        cabal test

### Local Variables: ***
### mode:yaml ***
### indent-tabs-mode: nil ***
### End: ***
